<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhraseApp
 *
 * PhraseApp API for the interaction with the PhraseApp localization platform
 *
 * OpenAPI spec version: 2.0
 * Contact: support@phraseapp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGet
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGet()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsGet
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsGet()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsIdDelete
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsIdGet
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsIdPatch
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsPost
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsPost()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsTermIdTranslationsIdDelete
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsTermIdTranslationsIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsTermIdTranslationsIdPatch
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsTermIdTranslationsIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesGlossaryIdTermsTermIdTranslationsPost
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesGlossaryIdTermsTermIdTranslationsPost()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesIdDelete
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesIdGet
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesIdPatch
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdGlossariesPost
     *
     * .
     *
     */
    public function testAccountsAccountIdGlossariesPost()
    {
    }

    /**
     * Test case for accountsAccountIdInvitationsGet
     *
     * .
     *
     */
    public function testAccountsAccountIdInvitationsGet()
    {
    }

    /**
     * Test case for accountsAccountIdInvitationsIdDelete
     *
     * .
     *
     */
    public function testAccountsAccountIdInvitationsIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdInvitationsIdGet
     *
     * .
     *
     */
    public function testAccountsAccountIdInvitationsIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdInvitationsIdPatch
     *
     * .
     *
     */
    public function testAccountsAccountIdInvitationsIdPatch()
    {
    }

    /**
     * Test case for accountsAccountIdInvitationsIdResendPost
     *
     * .
     *
     */
    public function testAccountsAccountIdInvitationsIdResendPost()
    {
    }

    /**
     * Test case for accountsAccountIdInvitationsPost
     *
     * .
     *
     */
    public function testAccountsAccountIdInvitationsPost()
    {
    }

    /**
     * Test case for accountsAccountIdMembersGet
     *
     * .
     *
     */
    public function testAccountsAccountIdMembersGet()
    {
    }

    /**
     * Test case for accountsAccountIdMembersIdDelete
     *
     * .
     *
     */
    public function testAccountsAccountIdMembersIdDelete()
    {
    }

    /**
     * Test case for accountsAccountIdMembersIdGet
     *
     * .
     *
     */
    public function testAccountsAccountIdMembersIdGet()
    {
    }

    /**
     * Test case for accountsAccountIdMembersIdPatch
     *
     * .
     *
     */
    public function testAccountsAccountIdMembersIdPatch()
    {
    }

    /**
     * Test case for accountsGet
     *
     * .
     *
     */
    public function testAccountsGet()
    {
    }

    /**
     * Test case for accountsIdGet
     *
     * .
     *
     */
    public function testAccountsIdGet()
    {
    }

    /**
     * Test case for authorizationsGet
     *
     * .
     *
     */
    public function testAuthorizationsGet()
    {
    }

    /**
     * Test case for authorizationsIdDelete
     *
     * .
     *
     */
    public function testAuthorizationsIdDelete()
    {
    }

    /**
     * Test case for authorizationsIdGet
     *
     * .
     *
     */
    public function testAuthorizationsIdGet()
    {
    }

    /**
     * Test case for authorizationsIdPatch
     *
     * .
     *
     */
    public function testAuthorizationsIdPatch()
    {
    }

    /**
     * Test case for authorizationsPost
     *
     * .
     *
     */
    public function testAuthorizationsPost()
    {
    }

    /**
     * Test case for formatsGet
     *
     * .
     *
     */
    public function testFormatsGet()
    {
    }

    /**
     * Test case for projectsGet
     *
     * .
     *
     */
    public function testProjectsGet()
    {
    }

    /**
     * Test case for projectsIdDelete
     *
     * .
     *
     */
    public function testProjectsIdDelete()
    {
    }

    /**
     * Test case for projectsIdGet
     *
     * .
     *
     */
    public function testProjectsIdGet()
    {
    }

    /**
     * Test case for projectsIdPatch
     *
     * .
     *
     */
    public function testProjectsIdPatch()
    {
    }

    /**
     * Test case for projectsPost
     *
     * .
     *
     */
    public function testProjectsPost()
    {
    }

    /**
     * Test case for projectsProjectIdBlacklistedKeysGet
     *
     * .
     *
     */
    public function testProjectsProjectIdBlacklistedKeysGet()
    {
    }

    /**
     * Test case for projectsProjectIdBlacklistedKeysIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdBlacklistedKeysIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdBlacklistedKeysIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdBlacklistedKeysIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdBlacklistedKeysIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdBlacklistedKeysIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdBlacklistedKeysPost
     *
     * .
     *
     */
    public function testProjectsProjectIdBlacklistedKeysPost()
    {
    }

    /**
     * Test case for projectsProjectIdKeysDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysDelete()
    {
    }

    /**
     * Test case for projectsProjectIdKeysGet
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysGet()
    {
    }

    /**
     * Test case for projectsProjectIdKeysIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdKeysIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdKeysIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsGet()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsIdReadDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsIdReadDelete()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsIdReadGet
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsIdReadGet()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsIdReadPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsIdReadPatch()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdCommentsPost
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdCommentsPost()
    {
    }

    /**
     * Test case for projectsProjectIdKeysKeyIdTranslationsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysKeyIdTranslationsGet()
    {
    }

    /**
     * Test case for projectsProjectIdKeysPost
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysPost()
    {
    }

    /**
     * Test case for projectsProjectIdKeysSearchPost
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysSearchPost()
    {
    }

    /**
     * Test case for projectsProjectIdKeysTagPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysTagPatch()
    {
    }

    /**
     * Test case for projectsProjectIdKeysUntagPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdKeysUntagPatch()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesGet
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesGet()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesIdDownloadGet
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesIdDownloadGet()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesLocaleIdTranslationsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesLocaleIdTranslationsGet()
    {
    }

    /**
     * Test case for projectsProjectIdLocalesPost
     *
     * .
     *
     */
    public function testProjectsProjectIdLocalesPost()
    {
    }

    /**
     * Test case for projectsProjectIdOrdersGet
     *
     * .
     *
     */
    public function testProjectsProjectIdOrdersGet()
    {
    }

    /**
     * Test case for projectsProjectIdOrdersIdConfirmPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdOrdersIdConfirmPatch()
    {
    }

    /**
     * Test case for projectsProjectIdOrdersIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdOrdersIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdOrdersIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdOrdersIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdOrdersPost
     *
     * .
     *
     */
    public function testProjectsProjectIdOrdersPost()
    {
    }

    /**
     * Test case for projectsProjectIdStyleguidesGet
     *
     * .
     *
     */
    public function testProjectsProjectIdStyleguidesGet()
    {
    }

    /**
     * Test case for projectsProjectIdStyleguidesIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdStyleguidesIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdStyleguidesIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdStyleguidesIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdStyleguidesIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdStyleguidesIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdStyleguidesPost
     *
     * .
     *
     */
    public function testProjectsProjectIdStyleguidesPost()
    {
    }

    /**
     * Test case for projectsProjectIdTagsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdTagsGet()
    {
    }

    /**
     * Test case for projectsProjectIdTagsNameDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdTagsNameDelete()
    {
    }

    /**
     * Test case for projectsProjectIdTagsNameGet
     *
     * .
     *
     */
    public function testProjectsProjectIdTagsNameGet()
    {
    }

    /**
     * Test case for projectsProjectIdTagsPost
     *
     * .
     *
     */
    public function testProjectsProjectIdTagsPost()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsExcludePatch
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsExcludePatch()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsGet()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsIncludePatch
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsIncludePatch()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsPost
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsPost()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsSearchPost
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsSearchPost()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsTranslationIdVersionsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsTranslationIdVersionsGet()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsTranslationIdVersionsIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsTranslationIdVersionsIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsUnverifyPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsUnverifyPatch()
    {
    }

    /**
     * Test case for projectsProjectIdTranslationsVerifyPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdTranslationsVerifyPatch()
    {
    }

    /**
     * Test case for projectsProjectIdUploadsGet
     *
     * .
     *
     */
    public function testProjectsProjectIdUploadsGet()
    {
    }

    /**
     * Test case for projectsProjectIdUploadsIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdUploadsIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdUploadsPost
     *
     * .
     *
     */
    public function testProjectsProjectIdUploadsPost()
    {
    }

    /**
     * Test case for projectsProjectIdWebhooksGet
     *
     * .
     *
     */
    public function testProjectsProjectIdWebhooksGet()
    {
    }

    /**
     * Test case for projectsProjectIdWebhooksIdDelete
     *
     * .
     *
     */
    public function testProjectsProjectIdWebhooksIdDelete()
    {
    }

    /**
     * Test case for projectsProjectIdWebhooksIdGet
     *
     * .
     *
     */
    public function testProjectsProjectIdWebhooksIdGet()
    {
    }

    /**
     * Test case for projectsProjectIdWebhooksIdPatch
     *
     * .
     *
     */
    public function testProjectsProjectIdWebhooksIdPatch()
    {
    }

    /**
     * Test case for projectsProjectIdWebhooksIdTestPost
     *
     * .
     *
     */
    public function testProjectsProjectIdWebhooksIdTestPost()
    {
    }

    /**
     * Test case for projectsProjectIdWebhooksPost
     *
     * .
     *
     */
    public function testProjectsProjectIdWebhooksPost()
    {
    }

    /**
     * Test case for userGet
     *
     * .
     *
     */
    public function testUserGet()
    {
    }
}
