# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Invitation(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'email': 'str',
        'role': 'str',
        'state': 'str',
        'created_at': 'datetime',
        'updated_at': 'datetime',
        'accepted_at': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'email': 'email',
        'role': 'role',
        'state': 'state',
        'created_at': 'created_at',
        'updated_at': 'updated_at',
        'accepted_at': 'accepted_at'
    }

    def __init__(self, id=None, email=None, role=None, state=None, created_at=None, updated_at=None, accepted_at=None):
        """
        Invitation - a model defined in Swagger
        """

        self._id = None
        self._email = None
        self._role = None
        self._state = None
        self._created_at = None
        self._updated_at = None
        self._accepted_at = None
        self.discriminator = None

        if id is not None:
          self.id = id
        if email is not None:
          self.email = email
        if role is not None:
          self.role = role
        if state is not None:
          self.state = state
        if created_at is not None:
          self.created_at = created_at
        if updated_at is not None:
          self.updated_at = updated_at
        if accepted_at is not None:
          self.accepted_at = accepted_at

    @property
    def id(self):
        """
        Gets the id of this Invitation.

        :return: The id of this Invitation.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Invitation.

        :param id: The id of this Invitation.
        :type: str
        """

        self._id = id

    @property
    def email(self):
        """
        Gets the email of this Invitation.

        :return: The email of this Invitation.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """
        Sets the email of this Invitation.

        :param email: The email of this Invitation.
        :type: str
        """

        self._email = email

    @property
    def role(self):
        """
        Gets the role of this Invitation.

        :return: The role of this Invitation.
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """
        Sets the role of this Invitation.

        :param role: The role of this Invitation.
        :type: str
        """

        self._role = role

    @property
    def state(self):
        """
        Gets the state of this Invitation.

        :return: The state of this Invitation.
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """
        Sets the state of this Invitation.

        :param state: The state of this Invitation.
        :type: str
        """

        self._state = state

    @property
    def created_at(self):
        """
        Gets the created_at of this Invitation.

        :return: The created_at of this Invitation.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this Invitation.

        :param created_at: The created_at of this Invitation.
        :type: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """
        Gets the updated_at of this Invitation.

        :return: The updated_at of this Invitation.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this Invitation.

        :param updated_at: The updated_at of this Invitation.
        :type: datetime
        """

        self._updated_at = updated_at

    @property
    def accepted_at(self):
        """
        Gets the accepted_at of this Invitation.

        :return: The accepted_at of this Invitation.
        :rtype: datetime
        """
        return self._accepted_at

    @accepted_at.setter
    def accepted_at(self, accepted_at):
        """
        Sets the accepted_at of this Invitation.

        :param accepted_at: The accepted_at of this Invitation.
        :type: datetime
        """

        self._accepted_at = accepted_at

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Invitation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
