# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class TranslationDetails(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'user': 'UserPreview',
        'word_count': 'int'
    }

    attribute_map = {
        'user': 'user',
        'word_count': 'word_count'
    }

    def __init__(self, user=None, word_count=None):
        """
        TranslationDetails - a model defined in Swagger
        """

        self._user = None
        self._word_count = None
        self.discriminator = None

        if user is not None:
          self.user = user
        if word_count is not None:
          self.word_count = word_count

    @property
    def user(self):
        """
        Gets the user of this TranslationDetails.

        :return: The user of this TranslationDetails.
        :rtype: UserPreview
        """
        return self._user

    @user.setter
    def user(self, user):
        """
        Sets the user of this TranslationDetails.

        :param user: The user of this TranslationDetails.
        :type: UserPreview
        """

        self._user = user

    @property
    def word_count(self):
        """
        Gets the word_count of this TranslationDetails.

        :return: The word_count of this TranslationDetails.
        :rtype: int
        """
        return self._word_count

    @word_count.setter
    def word_count(self, word_count):
        """
        Sets the word_count of this TranslationDetails.

        :param word_count: The word_count of this TranslationDetails.
        :type: int
        """

        self._word_count = word_count

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, TranslationDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
