<?php
/**
 * LocaleStatisticsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhraseApp
 *
 * PhraseApp API for the interaction with the PhraseApp localization platform
 *
 * OpenAPI spec version: 2.0
 * Contact: support@phraseapp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * LocaleStatisticsTest Class Doc Comment
 *
 * @category    Class */
// * @description LocaleStatistics
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LocaleStatisticsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LocaleStatistics"
     */
    public function testLocaleStatistics()
    {
    }

    /**
     * Test attribute "keys_total_count"
     */
    public function testPropertyKeysTotalCount()
    {
    }

    /**
     * Test attribute "keys_untranslated_count"
     */
    public function testPropertyKeysUntranslatedCount()
    {
    }

    /**
     * Test attribute "words_total_count"
     */
    public function testPropertyWordsTotalCount()
    {
    }

    /**
     * Test attribute "translations_completed_count"
     */
    public function testPropertyTranslationsCompletedCount()
    {
    }

    /**
     * Test attribute "translations_unverified_count"
     */
    public function testPropertyTranslationsUnverifiedCount()
    {
    }

    /**
     * Test attribute "unverified_words_count"
     */
    public function testPropertyUnverifiedWordsCount()
    {
    }

    /**
     * Test attribute "missing_words_count"
     */
    public function testPropertyMissingWordsCount()
    {
    }
}
