<?php
/**
 * StyleguideDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhraseApp
 *
 * PhraseApp API for the interaction with the PhraseApp localization platform
 *
 * OpenAPI spec version: 2.0
 * Contact: support@phraseapp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * StyleguideDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description StyleguideDetails
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class StyleguideDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "StyleguideDetails"
     */
    public function testStyleguideDetails()
    {
    }

    /**
     * Test attribute "public_url"
     */
    public function testPropertyPublicUrl()
    {
    }

    /**
     * Test attribute "audience"
     */
    public function testPropertyAudience()
    {
    }

    /**
     * Test attribute "target_audience"
     */
    public function testPropertyTargetAudience()
    {
    }

    /**
     * Test attribute "grammatical_person"
     */
    public function testPropertyGrammaticalPerson()
    {
    }

    /**
     * Test attribute "vocabulary_type"
     */
    public function testPropertyVocabularyType()
    {
    }

    /**
     * Test attribute "business"
     */
    public function testPropertyBusiness()
    {
    }

    /**
     * Test attribute "company_branding"
     */
    public function testPropertyCompanyBranding()
    {
    }

    /**
     * Test attribute "formatting"
     */
    public function testPropertyFormatting()
    {
    }

    /**
     * Test attribute "glossary_terms"
     */
    public function testPropertyGlossaryTerms()
    {
    }

    /**
     * Test attribute "grammar_consistency"
     */
    public function testPropertyGrammarConsistency()
    {
    }

    /**
     * Test attribute "literal_translation"
     */
    public function testPropertyLiteralTranslation()
    {
    }

    /**
     * Test attribute "overall_tone"
     */
    public function testPropertyOverallTone()
    {
    }

    /**
     * Test attribute "samples"
     */
    public function testPropertySamples()
    {
    }
}
