<?php
/**
 * TranslationKeyDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PhraseApp
 *
 * PhraseApp API for the interaction with the PhraseApp localization platform
 *
 * OpenAPI spec version: 2.0
 * Contact: support@phraseapp.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TranslationKeyDetailsTest Class Doc Comment
 *
 * @category    Class */
// * @description TranslationKeyDetails
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TranslationKeyDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TranslationKeyDetails"
     */
    public function testTranslationKeyDetails()
    {
    }

    /**
     * Test attribute "name_plural"
     */
    public function testPropertyNamePlural()
    {
    }

    /**
     * Test attribute "comments_count"
     */
    public function testPropertyCommentsCount()
    {
    }

    /**
     * Test attribute "max_characters_allowed"
     */
    public function testPropertyMaxCharactersAllowed()
    {
    }

    /**
     * Test attribute "screenshot_url"
     */
    public function testPropertyScreenshotUrl()
    {
    }

    /**
     * Test attribute "unformatted"
     */
    public function testPropertyUnformatted()
    {
    }

    /**
     * Test attribute "xml_space_preserve"
     */
    public function testPropertyXmlSpacePreserve()
    {
    }

    /**
     * Test attribute "original_file"
     */
    public function testPropertyOriginalFile()
    {
    }

    /**
     * Test attribute "format_value_type"
     */
    public function testPropertyFormatValueType()
    {
    }
}
