# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import phraseapp
from phraseapp.rest import ApiException
from phraseapp.models.translation_key import TranslationKey


class TestTranslationKey(unittest.TestCase):
    """ TranslationKey unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranslationKey(self):
        """
        Test TranslationKey
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = phraseapp.models.translation_key.TranslationKey()
        pass


if __name__ == '__main__':
    unittest.main()
