# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import phraseapp
from phraseapp.rest import ApiException
from phraseapp.models.translation_version_with_user import TranslationVersionWithUser


class TestTranslationVersionWithUser(unittest.TestCase):
    """ TranslationVersionWithUser unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTranslationVersionWithUser(self):
        """
        Test TranslationVersionWithUser
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = phraseapp.models.translation_version_with_user.TranslationVersionWithUser()
        pass


if __name__ == '__main__':
    unittest.main()
