# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import phraseapp
from phraseapp.rest import ApiException
from phraseapp.models.invitation import Invitation


class TestInvitation(unittest.TestCase):
    """ Invitation unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInvitation(self):
        """
        Test Invitation
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = phraseapp.models.invitation.Invitation()
        pass


if __name__ == '__main__':
    unittest.main()
