# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import phraseapp
from phraseapp.rest import ApiException
from phraseapp.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = phraseapp.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_accounts_account_id_glossaries_get(self):
        """
        Test case for accounts_account_id_glossaries_get

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_get(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_get

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_id_delete(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_id_delete

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_id_get(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_id_get

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_id_patch(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_id_patch

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_post(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_post

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_term_id_translations_id_delete(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_term_id_translations_id_delete

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_term_id_translations_id_patch(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_term_id_translations_id_patch

        
        """
        pass

    def test_accounts_account_id_glossaries_glossary_id_terms_term_id_translations_post(self):
        """
        Test case for accounts_account_id_glossaries_glossary_id_terms_term_id_translations_post

        
        """
        pass

    def test_accounts_account_id_glossaries_id_delete(self):
        """
        Test case for accounts_account_id_glossaries_id_delete

        
        """
        pass

    def test_accounts_account_id_glossaries_id_get(self):
        """
        Test case for accounts_account_id_glossaries_id_get

        
        """
        pass

    def test_accounts_account_id_glossaries_id_patch(self):
        """
        Test case for accounts_account_id_glossaries_id_patch

        
        """
        pass

    def test_accounts_account_id_glossaries_post(self):
        """
        Test case for accounts_account_id_glossaries_post

        
        """
        pass

    def test_accounts_account_id_invitations_get(self):
        """
        Test case for accounts_account_id_invitations_get

        
        """
        pass

    def test_accounts_account_id_invitations_id_delete(self):
        """
        Test case for accounts_account_id_invitations_id_delete

        
        """
        pass

    def test_accounts_account_id_invitations_id_get(self):
        """
        Test case for accounts_account_id_invitations_id_get

        
        """
        pass

    def test_accounts_account_id_invitations_id_patch(self):
        """
        Test case for accounts_account_id_invitations_id_patch

        
        """
        pass

    def test_accounts_account_id_invitations_id_resend_post(self):
        """
        Test case for accounts_account_id_invitations_id_resend_post

        
        """
        pass

    def test_accounts_account_id_invitations_post(self):
        """
        Test case for accounts_account_id_invitations_post

        
        """
        pass

    def test_accounts_account_id_members_get(self):
        """
        Test case for accounts_account_id_members_get

        
        """
        pass

    def test_accounts_account_id_members_id_delete(self):
        """
        Test case for accounts_account_id_members_id_delete

        
        """
        pass

    def test_accounts_account_id_members_id_get(self):
        """
        Test case for accounts_account_id_members_id_get

        
        """
        pass

    def test_accounts_account_id_members_id_patch(self):
        """
        Test case for accounts_account_id_members_id_patch

        
        """
        pass

    def test_accounts_get(self):
        """
        Test case for accounts_get

        
        """
        pass

    def test_accounts_id_get(self):
        """
        Test case for accounts_id_get

        
        """
        pass

    def test_authorizations_get(self):
        """
        Test case for authorizations_get

        
        """
        pass

    def test_authorizations_id_delete(self):
        """
        Test case for authorizations_id_delete

        
        """
        pass

    def test_authorizations_id_get(self):
        """
        Test case for authorizations_id_get

        
        """
        pass

    def test_authorizations_id_patch(self):
        """
        Test case for authorizations_id_patch

        
        """
        pass

    def test_authorizations_post(self):
        """
        Test case for authorizations_post

        
        """
        pass

    def test_formats_get(self):
        """
        Test case for formats_get

        
        """
        pass

    def test_projects_get(self):
        """
        Test case for projects_get

        
        """
        pass

    def test_projects_id_delete(self):
        """
        Test case for projects_id_delete

        
        """
        pass

    def test_projects_id_get(self):
        """
        Test case for projects_id_get

        
        """
        pass

    def test_projects_id_patch(self):
        """
        Test case for projects_id_patch

        
        """
        pass

    def test_projects_post(self):
        """
        Test case for projects_post

        
        """
        pass

    def test_projects_project_id_blacklisted_keys_get(self):
        """
        Test case for projects_project_id_blacklisted_keys_get

        
        """
        pass

    def test_projects_project_id_blacklisted_keys_id_delete(self):
        """
        Test case for projects_project_id_blacklisted_keys_id_delete

        
        """
        pass

    def test_projects_project_id_blacklisted_keys_id_get(self):
        """
        Test case for projects_project_id_blacklisted_keys_id_get

        
        """
        pass

    def test_projects_project_id_blacklisted_keys_id_patch(self):
        """
        Test case for projects_project_id_blacklisted_keys_id_patch

        
        """
        pass

    def test_projects_project_id_blacklisted_keys_post(self):
        """
        Test case for projects_project_id_blacklisted_keys_post

        
        """
        pass

    def test_projects_project_id_keys_delete(self):
        """
        Test case for projects_project_id_keys_delete

        
        """
        pass

    def test_projects_project_id_keys_get(self):
        """
        Test case for projects_project_id_keys_get

        
        """
        pass

    def test_projects_project_id_keys_id_delete(self):
        """
        Test case for projects_project_id_keys_id_delete

        
        """
        pass

    def test_projects_project_id_keys_id_get(self):
        """
        Test case for projects_project_id_keys_id_get

        
        """
        pass

    def test_projects_project_id_keys_id_patch(self):
        """
        Test case for projects_project_id_keys_id_patch

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_get(self):
        """
        Test case for projects_project_id_keys_key_id_comments_get

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_id_delete(self):
        """
        Test case for projects_project_id_keys_key_id_comments_id_delete

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_id_get(self):
        """
        Test case for projects_project_id_keys_key_id_comments_id_get

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_id_patch(self):
        """
        Test case for projects_project_id_keys_key_id_comments_id_patch

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_id_read_delete(self):
        """
        Test case for projects_project_id_keys_key_id_comments_id_read_delete

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_id_read_get(self):
        """
        Test case for projects_project_id_keys_key_id_comments_id_read_get

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_id_read_patch(self):
        """
        Test case for projects_project_id_keys_key_id_comments_id_read_patch

        
        """
        pass

    def test_projects_project_id_keys_key_id_comments_post(self):
        """
        Test case for projects_project_id_keys_key_id_comments_post

        
        """
        pass

    def test_projects_project_id_keys_key_id_translations_get(self):
        """
        Test case for projects_project_id_keys_key_id_translations_get

        
        """
        pass

    def test_projects_project_id_keys_post(self):
        """
        Test case for projects_project_id_keys_post

        
        """
        pass

    def test_projects_project_id_keys_search_post(self):
        """
        Test case for projects_project_id_keys_search_post

        
        """
        pass

    def test_projects_project_id_keys_tag_patch(self):
        """
        Test case for projects_project_id_keys_tag_patch

        
        """
        pass

    def test_projects_project_id_keys_untag_patch(self):
        """
        Test case for projects_project_id_keys_untag_patch

        
        """
        pass

    def test_projects_project_id_locales_get(self):
        """
        Test case for projects_project_id_locales_get

        
        """
        pass

    def test_projects_project_id_locales_id_delete(self):
        """
        Test case for projects_project_id_locales_id_delete

        
        """
        pass

    def test_projects_project_id_locales_id_download_get(self):
        """
        Test case for projects_project_id_locales_id_download_get

        
        """
        pass

    def test_projects_project_id_locales_id_get(self):
        """
        Test case for projects_project_id_locales_id_get

        
        """
        pass

    def test_projects_project_id_locales_id_patch(self):
        """
        Test case for projects_project_id_locales_id_patch

        
        """
        pass

    def test_projects_project_id_locales_locale_id_translations_get(self):
        """
        Test case for projects_project_id_locales_locale_id_translations_get

        
        """
        pass

    def test_projects_project_id_locales_post(self):
        """
        Test case for projects_project_id_locales_post

        
        """
        pass

    def test_projects_project_id_orders_get(self):
        """
        Test case for projects_project_id_orders_get

        
        """
        pass

    def test_projects_project_id_orders_id_confirm_patch(self):
        """
        Test case for projects_project_id_orders_id_confirm_patch

        
        """
        pass

    def test_projects_project_id_orders_id_delete(self):
        """
        Test case for projects_project_id_orders_id_delete

        
        """
        pass

    def test_projects_project_id_orders_id_get(self):
        """
        Test case for projects_project_id_orders_id_get

        
        """
        pass

    def test_projects_project_id_orders_post(self):
        """
        Test case for projects_project_id_orders_post

        
        """
        pass

    def test_projects_project_id_styleguides_get(self):
        """
        Test case for projects_project_id_styleguides_get

        
        """
        pass

    def test_projects_project_id_styleguides_id_delete(self):
        """
        Test case for projects_project_id_styleguides_id_delete

        
        """
        pass

    def test_projects_project_id_styleguides_id_get(self):
        """
        Test case for projects_project_id_styleguides_id_get

        
        """
        pass

    def test_projects_project_id_styleguides_id_patch(self):
        """
        Test case for projects_project_id_styleguides_id_patch

        
        """
        pass

    def test_projects_project_id_styleguides_post(self):
        """
        Test case for projects_project_id_styleguides_post

        
        """
        pass

    def test_projects_project_id_tags_get(self):
        """
        Test case for projects_project_id_tags_get

        
        """
        pass

    def test_projects_project_id_tags_name_delete(self):
        """
        Test case for projects_project_id_tags_name_delete

        
        """
        pass

    def test_projects_project_id_tags_name_get(self):
        """
        Test case for projects_project_id_tags_name_get

        
        """
        pass

    def test_projects_project_id_tags_post(self):
        """
        Test case for projects_project_id_tags_post

        
        """
        pass

    def test_projects_project_id_translations_exclude_patch(self):
        """
        Test case for projects_project_id_translations_exclude_patch

        
        """
        pass

    def test_projects_project_id_translations_get(self):
        """
        Test case for projects_project_id_translations_get

        
        """
        pass

    def test_projects_project_id_translations_id_get(self):
        """
        Test case for projects_project_id_translations_id_get

        
        """
        pass

    def test_projects_project_id_translations_id_patch(self):
        """
        Test case for projects_project_id_translations_id_patch

        
        """
        pass

    def test_projects_project_id_translations_include_patch(self):
        """
        Test case for projects_project_id_translations_include_patch

        
        """
        pass

    def test_projects_project_id_translations_post(self):
        """
        Test case for projects_project_id_translations_post

        
        """
        pass

    def test_projects_project_id_translations_search_post(self):
        """
        Test case for projects_project_id_translations_search_post

        
        """
        pass

    def test_projects_project_id_translations_translation_id_versions_get(self):
        """
        Test case for projects_project_id_translations_translation_id_versions_get

        
        """
        pass

    def test_projects_project_id_translations_translation_id_versions_id_get(self):
        """
        Test case for projects_project_id_translations_translation_id_versions_id_get

        
        """
        pass

    def test_projects_project_id_translations_unverify_patch(self):
        """
        Test case for projects_project_id_translations_unverify_patch

        
        """
        pass

    def test_projects_project_id_translations_verify_patch(self):
        """
        Test case for projects_project_id_translations_verify_patch

        
        """
        pass

    def test_projects_project_id_uploads_get(self):
        """
        Test case for projects_project_id_uploads_get

        
        """
        pass

    def test_projects_project_id_uploads_id_get(self):
        """
        Test case for projects_project_id_uploads_id_get

        
        """
        pass

    def test_projects_project_id_uploads_post(self):
        """
        Test case for projects_project_id_uploads_post

        
        """
        pass

    def test_projects_project_id_webhooks_get(self):
        """
        Test case for projects_project_id_webhooks_get

        
        """
        pass

    def test_projects_project_id_webhooks_id_delete(self):
        """
        Test case for projects_project_id_webhooks_id_delete

        
        """
        pass

    def test_projects_project_id_webhooks_id_get(self):
        """
        Test case for projects_project_id_webhooks_id_get

        
        """
        pass

    def test_projects_project_id_webhooks_id_patch(self):
        """
        Test case for projects_project_id_webhooks_id_patch

        
        """
        pass

    def test_projects_project_id_webhooks_id_test_post(self):
        """
        Test case for projects_project_id_webhooks_id_test_post

        
        """
        pass

    def test_projects_project_id_webhooks_post(self):
        """
        Test case for projects_project_id_webhooks_post

        
        """
        pass

    def test_user_get(self):
        """
        Test case for user_get

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
