# coding: utf-8

"""
    PhraseApp

    PhraseApp API for the interaction with the PhraseApp localization platform

    OpenAPI spec version: 2.0
    Contact: support@phraseapp.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import phraseapp
from phraseapp.rest import ApiException
from phraseapp.models.format import Format


class TestFormat(unittest.TestCase):
    """ Format unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFormat(self):
        """
        Test Format
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = phraseapp.models.format.Format()
        pass


if __name__ == '__main__':
    unittest.main()
